include:
  - board: seeeduino_xiao_ble
    shield: totem_left
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    snippet: zmk-usb-logging
# there is no settingsreset (needed) for the XIAO
# - board: seeeduino_xiao_ble
#   shield: settings_reset
